---
services:
  hawser:
    image: 'ghcr.io/finsys/hawser:0.2.39'
    container_name: hawser
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "${BIND_IP}:2376:2376"
    volumes:
      - /data/stacks:/data/stacks
      - /var/run/docker.sock:/var/run/docker.sock
      - /llm:/llm
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.hawser.loadbalancer.server.port=2376"
      - "traefik.http.routers.hawser.entrypoints=https"
      - "traefik.http.routers.hawser.tls=true"
      - "traefik.http.routers.hawser.tls.certresolver=letsencrypt"
      - "traefik.http.routers.hawser.rule=Host(`hawser-${NODE_NAME}.${DOMAIN}`)"
      - "traefik.http.routers.hawser.service=hawser"

  traefik-kop:
    image: ghcr.io/jittering/traefik-kop:latest
    container_name: traefik-kop
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - REDIS_ADDR=${REDIS_ADDR}
      - BIND_IP=${BIND_IP}

networks:
  proxy:
    external: true
